### ISSUE TITLE
Simple question about PDW

### ISSUE THREAD

**Issue by nau4k** [Discriminator/PDW#16]
Hi everyone I have to send pocsag text message using rpitx by @F5OEO [https://github.com/F5OEO/rpitx](url) and receive with PDW software and finally I can send text, sometimes I receive text same like i send but sometimes im not receiving like i send. I mean didn't receive the text clearly like at the pitcure. i send text "Alhamdulillah" from rpitx and on receiver sometimes im not receive Alhamdulillah, somtimes Alhamt@ulillah, Al@amdulillah, etc. can someone explain to me what happend and what is causing it?
![WhatsApp Image 2023-06-09 at 16 52 36](https://github.com/Discriminator/PDW/assets/116134351/290b5464-98bf-4ed4-b306-c706e853dccc)

**Comment by davide1995** [comment]
Just play a little bit with the volume by increasing it or decreasing
