### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by Slugman1983** [Discriminator/PDW#7]
Hi,

I have just a one thing that bothers me, logfiles are saved in ANSI
how can i save logfiles in utf-8?
If I open files with texteditor and save as utf-8 its working but I have lots of logfiles and also automation script so I can't do this all the time.

If anyone could help please.
just save as utf-8 no need to change or process characters because they are fine, tested it.

**Comment by jklnz** [comment]
Hey @jebacina I think I may have an idea on how to fix this, what operating system will you be running PDW on?

**Comment by jebacina** [comment]
windows 7

**Comment by jklnz** [comment]
ok cool, i'll see if my changes work.
are you able to recompile from source or do you need me to give you a pdw.exe?

**Comment by jebacina** [comment]
well it would be nice to see how you did it also :+1:
