### ISSUE TITLE
delimitor

### ISSUE THREAD

**Issue by Slugman1983** [Discriminator/PDW#9]
Hi,

is it possible to change logfile delimiter from space to example ; ?

it will make it simpler for importing.

or do you have any "live" import to mySQL python or any other script available?

Regards

**Comment by jklnz** [comment]
There is no live importing but you can just set PDW to auto launch a batch file or custom program after every message is received and use that to import the data in to your mySQL.

**Comment by jebacina** [comment]
Well I have set phyton to watch dir of logfiles, so when message comes it knows which logfile is changed. But I would need delimiter to make it easier to import in DB.

How would I be able to achieve that in your case?

**Comment by jklnz** [comment]
![filter command line](https://user-images.githubusercontent.com/26646690/52174258-2d7b3c80-27f6-11e9-9d92-6bab9b9c08bc.PNG)
![filter set up](https://user-images.githubusercontent.com/26646690/52174259-2d7b3c80-27f6-11e9-9062-db03ffeec024.PNG)



you can set up what you desire by setting up filters and using the filter command line.

Basically, add a filter that matches the type for your network (e.g. mine is FLEX so I added a flex filter), see the screen cap.

Then go to Filter Options and set it to enable command line, browse for the file you want it to launch, and in arguments enter the arguments to pass. Then every time a message matches your filter it will launch your program to use the message data (e,g, to upload to a webservice)

**Comment by jebacina** [comment]
I want to output all messages into server, at the moment I do filtering with php script.

**Comment by jklnz** [comment]
If you set the filter to ??????? it will match all messages so all messages get sent to your script.

PagerProcesser.exe is a custom program I wrote in C# that picks up the message and sends it to my server.

**Comment by jebacina** [comment]
aha ok, possible to share that program?

**Comment by jklnz** [comment]
I will clean it up a bit and share it for you

**Comment by jebacina** [comment]
Okay thank you very much.

**Comment by jklnz** [comment]
Hi @jebacina, check out my repo: https://github.com/jklnz/pagerprocessor

**Comment by jebacina** [comment]
I have checked the file and gave me pretty idea how to do this in powershell.
Thanks for help, Regards

**Comment by jklnz** [comment]
Good to hear, don't hesitate to ask if you need anything else.
